### PR TITLE
A6020: Use Android Go configurations

### PR DESCRIPTION
**Pull request by Thespartann**
Improves performance overall, reduces rom size :)

### CODE REVIEW

**Comment by adithya2306** [comment]
> Improves performance overall, reduces rom size :)

Last time I checked, I couldn't even get to compile it (r2 tag). Can you try once?
Also use go_defaults_common.mk instead of go_defaults.mk as the latter is just an empty makefile which includes the former anyway

**Comment by Thespartann** [comment]
Hecc, i screwd the naming up
But yeah i did try go on pie and it worked really good, i'll re-push tomorrow and try a build

**Comment by Thespartann** [comment]
Actually just checked now and go_defaults.mk links to go_defaults_common and go_defaults.prop so it should actually just be used like this :)

**Comment by adithya2306** [comment]
> Actually just checked now and go_defaults.mk links to go_defaults_common and go_defaults.prop so it should actually just be used like this :)

Were you able to build?

**Comment by Thespartann** [comment]
Android Go makes Android Q bootloop for now, will check again in one month

**Pull request closed without merging**
